apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-app
    tier: proxy
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
