apiVersion: v1
kind: Service
metadata: 
  name: proxy-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30080
  selector:
    app: my-nginx-app
    tier: frontend-proxy
